// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Entry struct {
	ID        int64
	UserID    int64
	WorkoutID int64
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Exercise struct {
	ID        int64
	UserID    int64
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type User struct {
	ID        int64
	Email     string
	Hash      []byte
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Workout struct {
	ID        int64
	UserID    int64
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type WorkoutsExercise struct {
	ID         int64
	UserID     int64
	WorkoutID  int64
	ExerciseID int64
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}
