// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: check.sql

package db

import (
	"context"
)

const check = `-- name: check :exec
SELECT 1
`

func (q *Queries) check(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, check)
	return err
}
