// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package db

import (
	"context"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
  name
) VALUES (?)
RETURNING id, name, workout_id, created_at, updated_at
`

func (q *Queries) CreateEntry(ctx context.Context, name string) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry, name)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkoutID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEntryByID = `-- name: DeleteEntryByID :exec
DELETE FROM entries
WHERE id = ?
`

func (q *Queries) DeleteEntryByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntryByID, id)
	return err
}

const getEntryByID = `-- name: GetEntryByID :one
SELECT id, name, workout_id, created_at, updated_at
FROM entries
WHERE id = ?
`

func (q *Queries) GetEntryByID(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntryByID, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkoutID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllEntries = `-- name: ListAllEntries :many
SELECT id, name, workout_id, created_at, updated_at
FROM entries
`

func (q *Queries) ListAllEntries(ctx context.Context) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listAllEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WorkoutID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE entries
SET name = ?
WHERE id = ?
RETURNING id, name, workout_id, created_at, updated_at
`

type UpdateEntryParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, updateEntry, arg.Name, arg.ID)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkoutID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
