// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package db

import (
	"context"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
  user_id,
  workout_id,
  name
) VALUES (?, ?, ?)
RETURNING id, user_id, workout_id, name, created_at, updated_at
`

type CreateEntryParams struct {
	UserID    int64
	WorkoutID int64
	Name      string
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry, arg.UserID, arg.WorkoutID, arg.Name)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEntryByID = `-- name: DeleteEntryByID :exec
DELETE FROM entries
WHERE id = ?
AND user_id = ?
`

type DeleteEntryByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteEntryByID(ctx context.Context, arg DeleteEntryByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteEntryByID, arg.ID, arg.UserID)
	return err
}

const getEntryByID = `-- name: GetEntryByID :one
SELECT id, user_id, workout_id, name, created_at, updated_at
FROM entries
WHERE id = ?
AND user_id = ?
`

type GetEntryByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetEntryByID(ctx context.Context, arg GetEntryByIDParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntryByID, arg.ID, arg.UserID)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllEntries = `-- name: ListAllEntries :many
SELECT id, user_id, workout_id, name, created_at, updated_at
FROM entries
WHERE user_id = ?
`

func (q *Queries) ListAllEntries(ctx context.Context, userID int64) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listAllEntries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkoutID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE entries
SET name = ?
WHERE id = ?
AND user_id = ?
RETURNING id, user_id, workout_id, name, created_at, updated_at
`

type UpdateEntryParams struct {
	Name   string
	ID     int64
	UserID int64
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, updateEntry, arg.Name, arg.ID, arg.UserID)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
