// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercises.sql

package db

import (
	"context"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (
  name
) VALUES (?)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateExercise(ctx context.Context, name string) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, createExercise, name)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExerciseByID = `-- name: DeleteExerciseByID :exec
DELETE FROM exercises
WHERE id = ?
`

func (q *Queries) DeleteExerciseByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExerciseByID, id)
	return err
}

const getExerciseByID = `-- name: GetExerciseByID :one
SELECT id, name, created_at, updated_at
FROM exercises
WHERE id = ?
`

func (q *Queries) GetExerciseByID(ctx context.Context, id int64) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, getExerciseByID, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllExercises = `-- name: ListAllExercises :many
SELECT id, name, created_at, updated_at
FROM exercises
`

func (q *Queries) ListAllExercises(ctx context.Context) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, listAllExercises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExercise = `-- name: UpdateExercise :one
UPDATE exercises
SET name = ?
WHERE id = ?
RETURNING id, name, created_at, updated_at
`

type UpdateExerciseParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateExercise(ctx context.Context, arg UpdateExerciseParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, updateExercise, arg.Name, arg.ID)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
