// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercises.sql

package db

import (
	"context"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (
  user_id,
  name
) VALUES (?, ?)
RETURNING id, user_id, name, created_at, updated_at
`

type CreateExerciseParams struct {
	UserID int64
	Name   string
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, createExercise, arg.UserID, arg.Name)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExerciseByID = `-- name: DeleteExerciseByID :exec
DELETE FROM exercises
WHERE id = ?
AND user_id = ?
`

type DeleteExerciseByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteExerciseByID(ctx context.Context, arg DeleteExerciseByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteExerciseByID, arg.ID, arg.UserID)
	return err
}

const getExerciseByID = `-- name: GetExerciseByID :one
SELECT id, user_id, name, created_at, updated_at
FROM exercises
WHERE id = ?
AND user_id = ?
`

type GetExerciseByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetExerciseByID(ctx context.Context, arg GetExerciseByIDParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, getExerciseByID, arg.ID, arg.UserID)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllExercises = `-- name: ListAllExercises :many
SELECT id, user_id, name, created_at, updated_at
FROM exercises
WHERE user_id = ?
`

func (q *Queries) ListAllExercises(ctx context.Context, userID int64) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, listAllExercises, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExercise = `-- name: UpdateExercise :one
UPDATE exercises
SET name = ?
WHERE id = ?
AND user_id = ?
RETURNING id, user_id, name, created_at, updated_at
`

type UpdateExerciseParams struct {
	Name   string
	ID     int64
	UserID int64
}

func (q *Queries) UpdateExercise(ctx context.Context, arg UpdateExerciseParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, updateExercise, arg.Name, arg.ID, arg.UserID)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
