// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Entry struct {
	ID        int64
	Name      string
	WorkoutID int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Exercise struct {
	ID        int64
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Workout struct {
	ID        int64
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type WorkoutExercise struct {
	ID         int64
	WorkoutID  int64
	ExerciseID int64
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}
