// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workouts.sql

package db

import (
	"context"
)

const createWorkout = `-- name: CreateWorkout :one
INSERT INTO workouts (
  name
) VALUES (?)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateWorkout(ctx context.Context, name string) (Workout, error) {
	row := q.db.QueryRowContext(ctx, createWorkout, name)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkoutByID = `-- name: DeleteWorkoutByID :exec
DELETE FROM workouts
WHERE id = ?
`

func (q *Queries) DeleteWorkoutByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWorkoutByID, id)
	return err
}

const getWorkoutByID = `-- name: GetWorkoutByID :one
SELECT id, name, created_at, updated_at
FROM workouts
WHERE id = ?
`

func (q *Queries) GetWorkoutByID(ctx context.Context, id int64) (Workout, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutByID, id)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllWorkouts = `-- name: ListAllWorkouts :many
SELECT id, name, created_at, updated_at
FROM workouts
`

func (q *Queries) ListAllWorkouts(ctx context.Context) ([]Workout, error) {
	rows, err := q.db.QueryContext(ctx, listAllWorkouts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkout = `-- name: UpdateWorkout :one
UPDATE workouts
SET name = ?
WHERE id = ?
RETURNING id, name, created_at, updated_at
`

type UpdateWorkoutParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateWorkout(ctx context.Context, arg UpdateWorkoutParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, updateWorkout, arg.Name, arg.ID)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
