// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workouts_exercises.sql

package db

import (
	"context"
	"database/sql"
)

const createWorkoutExercise = `-- name: CreateWorkoutExercise :one
INSERT INTO workouts_exercises (
  user_id,
  workout_id,
  exercise_id
) VALUES (?, ?, ?)
RETURNING id, user_id, workout_id, exercise_id, created_at, updated_at
`

type CreateWorkoutExerciseParams struct {
	UserID     int64
	WorkoutID  int64
	ExerciseID int64
}

func (q *Queries) CreateWorkoutExercise(ctx context.Context, arg CreateWorkoutExerciseParams) (WorkoutsExercise, error) {
	row := q.db.QueryRowContext(ctx, createWorkoutExercise, arg.UserID, arg.WorkoutID, arg.ExerciseID)
	var i WorkoutsExercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutID,
		&i.ExerciseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkoutExerciseByID = `-- name: DeleteWorkoutExerciseByID :exec
DELETE FROM workouts_exercises
WHERE id = ?
AND user_id = ?
`

type DeleteWorkoutExerciseByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteWorkoutExerciseByID(ctx context.Context, arg DeleteWorkoutExerciseByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkoutExerciseByID, arg.ID, arg.UserID)
	return err
}

const getWorkoutExerciseById = `-- name: GetWorkoutExerciseById :one
SELECT id, user_id, workout_id, exercise_id, created_at, updated_at
FROM workouts_exercises
WHERE id = ?
AND user_id = ?
`

type GetWorkoutExerciseByIdParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetWorkoutExerciseById(ctx context.Context, arg GetWorkoutExerciseByIdParams) (WorkoutsExercise, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutExerciseById, arg.ID, arg.UserID)
	var i WorkoutsExercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutID,
		&i.ExerciseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExercisesByWorkoutId = `-- name: ListExercisesByWorkoutId :many
SELECT exercises.id, exercises.user_id, exercises.name, exercises.created_at, exercises.updated_at, workouts_exercises.id as workout_exercise_id
FROM exercises
JOIN workouts_exercises ON workouts_exercises.exercise_id = exercises.id
WHERE workouts_exercises.workout_id = ?
AND workouts_exercises.user_id = ?
`

type ListExercisesByWorkoutIdParams struct {
	WorkoutID int64
	UserID    int64
}

type ListExercisesByWorkoutIdRow struct {
	ID                int64
	UserID            int64
	Name              string
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	WorkoutExerciseID int64
}

func (q *Queries) ListExercisesByWorkoutId(ctx context.Context, arg ListExercisesByWorkoutIdParams) ([]ListExercisesByWorkoutIdRow, error) {
	rows, err := q.db.QueryContext(ctx, listExercisesByWorkoutId, arg.WorkoutID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExercisesByWorkoutIdRow
	for rows.Next() {
		var i ListExercisesByWorkoutIdRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkoutExerciseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
