// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workouts_exercises.sql

package db

import (
	"context"
)

const createWorkoutExercise = `-- name: CreateWorkoutExercise :one
INSERT INTO workouts_exercises (
  user_id,
  workout_id,
  exercise_id
) VALUES (?, ?, ?)
RETURNING id, user_id, workout_id, exercise_id, created_at, updated_at
`

type CreateWorkoutExerciseParams struct {
	UserID     int64
	WorkoutID  int64
	ExerciseID int64
}

func (q *Queries) CreateWorkoutExercise(ctx context.Context, arg CreateWorkoutExerciseParams) (WorkoutsExercise, error) {
	row := q.db.QueryRowContext(ctx, createWorkoutExercise, arg.UserID, arg.WorkoutID, arg.ExerciseID)
	var i WorkoutsExercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutID,
		&i.ExerciseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkoutExerciseByID = `-- name: DeleteWorkoutExerciseByID :exec
DELETE FROM workouts_exercises
WHERE id = ?
AND user_id = ?
`

type DeleteWorkoutExerciseByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteWorkoutExerciseByID(ctx context.Context, arg DeleteWorkoutExerciseByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkoutExerciseByID, arg.ID, arg.UserID)
	return err
}
